### ISSUE TITLE
.env sample?

### ISSUE THREAD

**Issue by pomazanbohdan** [ingadhoc/docker-odoo-saas-project#9]
add pls

**Comment by jjscarafia** [comment]
This project is customized and hard coded to our way of deploying, building images, etc. The main project that builds the odoo image is https://github.com/ingadhoc/docker-odoo
And this would be a sample of a project that extends that base odoo image: https://github.com/ingadhoc/docker-odoo-argentina-ce.

In this case:
This is the setup of docker hub to build odoo baseimage:
![image](https://user-images.githubusercontent.com/3016656/97690611-f776f500-1a7b-11eb-86ef-7f55bfcbf46c.png)


And this is the setup on docker hub to extend previous image with custom repos
![image](https://user-images.githubusercontent.com/3016656/97690696-18d7e100-1a7c-11eb-9774-742bbe7daec7.png)


Hope it helps

**Comment by jjscarafia** [comment]
note that "adhoc/odoo-ce" is the name given on the docker hub repository for the first image (the one only with odoo)
